create table if not exists public.company_news_summaries (
  id bigint generated by default as identity primary key,
  symbol text not null default '',
  summary_date date not null,
  model text not null,
  news_count integer not null default 0,
  summary_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists company_news_summaries_symbol_date_key
on public.company_news_summaries (symbol, summary_date);

create index if not exists company_news_summaries_symbol_summary_date_idx
on public.company_news_summaries (symbol, summary_date desc);
