create table if not exists public.market_news (
  id bigint generated by default as identity primary key,
  finnhub_id bigint not null,
  category text not null default 'general',
  news_datetime timestamptz not null,
  headline text not null,
  image_url text not null default '',
  related text not null default '',
  source text not null default '',
  summary text not null default '',
  url text not null,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  constraint market_news_finnhub_id_key unique (finnhub_id)
);

create index if not exists market_news_category_datetime_idx
on public.market_news (category, news_datetime desc);
