create table if not exists public.market_news_summaries (
  id bigint generated by default as identity primary key,
  category text not null default 'general',
  model text not null,
  news_count integer not null default 0,
  summary_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists market_news_summaries_category_key
on public.market_news_summaries (category);

create index if not exists market_news_summaries_category_created_at_idx
on public.market_news_summaries (category, created_at desc);
