


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid" DEFAULT NULL::"uuid") RETURNS integer
    LANGUAGE "plpgsql"
    AS $$
declare
  affected_rows integer := 0;
begin
  with latest_rate as (
    select coalesce(
      (
        select er.rate
        from public.exchange_rates er
        where er.currency_pair = 'USD/KRW'
        order by er.recorded_at desc
        limit 1
      ),
      1.0
    ) as usd_krw
  ),
  holding_agg as (
    select
      h.asset_id,
      sum(h.quantity * h.average_price) as purchase_krw,
      sum(
        (h.quantity * h.current_price) *
        case
          when upper(coalesce(h.currency_code, 'KRW')) = 'USD'
            then lr.usd_krw
          else 1.0
        end
      ) as valuation_krw
    from public.holdings h
    cross join latest_rate lr
    where h.deleted_at is null
      and (target_user_id is null or h.user_id = target_user_id)
    group by h.asset_id
  ),
  computed as (
    select
      a.id as asset_id,
      coalesce(ha.purchase_krw, 0)::double precision as purchase_krw,
      coalesce(ha.valuation_krw, 0)::double precision as valuation_krw,
      (coalesce(ha.valuation_krw, 0) - coalesce(ha.purchase_krw, 0))::double precision as profit_krw,
      (
        case
          when coalesce(ha.purchase_krw, 0) = 0 then 0
          else ((coalesce(ha.valuation_krw, 0) - coalesce(ha.purchase_krw, 0)) / ha.purchase_krw) * 100
        end
      )::double precision as profit_rate
    from public.assets a
    left join holding_agg ha on ha.asset_id = a.id
    where a.deleted_at is null
      and (target_user_id is null or a.user_id = target_user_id)
  )
  update public.assets a
  set
    purchase_krw = c.purchase_krw,
    valuation_krw = c.valuation_krw,
    profit_krw = c.profit_krw,
    profit_rate = c.profit_rate,
    value = case
      when c.valuation_krw < 0
        then '-₩' || to_char(abs(round(c.valuation_krw))::numeric, 'FM999,999,999,999,999,990')
      else '₩' || to_char(round(c.valuation_krw)::numeric, 'FM999,999,999,999,999,990')
    end,
    change = (
      case
        when c.profit_rate >= 0 then '+'
        else ''
      end
    ) || to_char(round(c.profit_rate::numeric, 1), 'FM999999999990.0') || '%',
    metrics_updated_at = now()
  from computed c
  where a.id = c.asset_id;

  get diagnostics affected_rows = row_count;
  return affected_rows;
end;
$$;


ALTER FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid") OWNER TO "postgres";


COMMENT ON FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid") IS 'Recomputes assets numeric metrics and display fields(value/change) from non-deleted holdings. USD holdings are converted with latest USD/KRW exchange rate.';



CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."api_tokens" (
    "provider" "text" NOT NULL,
    "access_token" "text" NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."api_tokens" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."asset_allocation_targets" (
    "id" bigint NOT NULL,
    "asset_id" bigint NOT NULL,
    "target_ratio" double precision NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."asset_allocation_targets" OWNER TO "postgres";


ALTER TABLE "public"."asset_allocation_targets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."asset_allocation_targets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."assets" (
    "id" bigint NOT NULL,
    "asset_type" "text" DEFAULT '주식'::"text" NOT NULL,
    "title" "text" NOT NULL,
    "alias" "text" DEFAULT ''::"text" NOT NULL,
    "currency_code" "text" DEFAULT 'KRW'::"text" NOT NULL,
    "value" "text" NOT NULL,
    "change" "text" NOT NULL,
    "icon_code_point" integer NOT NULL,
    "quantity_label" "text" NOT NULL,
    "quantity_value" "text" NOT NULL,
    "average_label" "text" NOT NULL,
    "average_value" "text" NOT NULL,
    "note" "text" NOT NULL,
    "sort_order" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone,
    "valuation_krw" double precision DEFAULT 0 NOT NULL,
    "purchase_krw" double precision DEFAULT 0 NOT NULL,
    "profit_krw" double precision DEFAULT 0 NOT NULL,
    "profit_rate" double precision DEFAULT 0 NOT NULL,
    "metrics_updated_at" timestamp with time zone
);


ALTER TABLE "public"."assets" OWNER TO "postgres";


COMMENT ON COLUMN "public"."assets"."valuation_krw" IS 'Derived total valuation in KRW from non-deleted holdings.';



COMMENT ON COLUMN "public"."assets"."purchase_krw" IS 'Derived total purchase amount in KRW from non-deleted holdings.';



COMMENT ON COLUMN "public"."assets"."profit_krw" IS 'Derived profit in KRW (valuation_krw - purchase_krw).';



COMMENT ON COLUMN "public"."assets"."profit_rate" IS 'Derived profit rate in percent. 0 when purchase_krw is 0.';



COMMENT ON COLUMN "public"."assets"."metrics_updated_at" IS 'Timestamp when derived asset metrics were last refreshed.';



ALTER TABLE "public"."assets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."assets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cash_accounts" (
    "id" bigint NOT NULL,
    "asset_id" bigint NOT NULL,
    "currency_code" "text" DEFAULT 'KRW'::"text" NOT NULL,
    "name" "text" NOT NULL,
    "base_balance" double precision DEFAULT 0 NOT NULL,
    "balance" double precision DEFAULT 0 NOT NULL,
    "note" "text" DEFAULT ''::"text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."cash_accounts" OWNER TO "postgres";


ALTER TABLE "public"."cash_accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cash_accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cash_transactions" (
    "id" bigint NOT NULL,
    "asset_id" bigint NOT NULL,
    "cash_account_id" bigint NOT NULL,
    "linked_transaction_id" bigint,
    "date" "date" NOT NULL,
    "type" "text" NOT NULL,
    "name" "text" NOT NULL,
    "amount" "text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."cash_transactions" OWNER TO "postgres";


ALTER TABLE "public"."cash_transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cash_transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company_news" (
    "id" bigint NOT NULL,
    "symbol" "text" NOT NULL,
    "finnhub_id" bigint NOT NULL,
    "news_datetime" timestamp with time zone NOT NULL,
    "headline" "text" NOT NULL,
    "image_url" "text" DEFAULT ''::"text" NOT NULL,
    "category" "text" DEFAULT ''::"text" NOT NULL,
    "related" "text" DEFAULT ''::"text" NOT NULL,
    "source" "text" DEFAULT ''::"text" NOT NULL,
    "summary" "text" DEFAULT ''::"text" NOT NULL,
    "url" "text" NOT NULL,
    "fetched_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "raw_payload" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL
);


ALTER TABLE "public"."company_news" OWNER TO "postgres";


ALTER TABLE "public"."company_news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company_news_summaries" (
    "id" bigint NOT NULL,
    "company_name" "text" DEFAULT ''::"text" NOT NULL,
    "symbol" "text" DEFAULT ''::"text" NOT NULL,
    "summary_date" "date" NOT NULL,
    "model" "text" NOT NULL,
    "news_count" integer DEFAULT 0 NOT NULL,
    "summary_json" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."company_news_summaries" OWNER TO "postgres";


ALTER TABLE "public"."company_news_summaries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_news_summaries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."daily_portfolio_snapshot_cash_accounts" (
    "id" bigint NOT NULL,
    "snapshot_id" bigint NOT NULL,
    "asset_id" bigint,
    "asset_title" "text" NOT NULL,
    "cash_account_id" bigint,
    "cash_account_name" "text" NOT NULL,
    "currency_code" "text" NOT NULL,
    "balance" double precision NOT NULL,
    "note" "text" DEFAULT ''::"text" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."daily_portfolio_snapshot_cash_accounts" OWNER TO "postgres";


ALTER TABLE "public"."daily_portfolio_snapshot_cash_accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."daily_portfolio_snapshot_cash_accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."daily_portfolio_snapshot_holding_items" (
    "id" bigint NOT NULL,
    "snapshot_id" bigint NOT NULL,
    "asset_id" bigint,
    "asset_title" "text" NOT NULL,
    "holding_id" bigint,
    "holding_name" "text" NOT NULL,
    "holding_symbol" "text" NOT NULL,
    "currency_code" "text" NOT NULL,
    "quantity" double precision NOT NULL,
    "total_purchase_amount" double precision NOT NULL,
    "total_valuation_amount" double precision NOT NULL,
    "profit_amount" double precision NOT NULL,
    "profit_rate" double precision NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."daily_portfolio_snapshot_holding_items" OWNER TO "postgres";


ALTER TABLE "public"."daily_portfolio_snapshot_holding_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."daily_portfolio_snapshot_holding_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."daily_portfolio_snapshot_items" (
    "id" bigint NOT NULL,
    "snapshot_id" bigint NOT NULL,
    "asset_id" bigint NOT NULL,
    "asset_title" "text" NOT NULL,
    "total_purchase_amount" double precision NOT NULL,
    "total_valuation_amount" double precision NOT NULL,
    "profit_amount" double precision NOT NULL,
    "profit_rate" double precision NOT NULL,
    "holding_count" integer NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."daily_portfolio_snapshot_items" OWNER TO "postgres";


ALTER TABLE "public"."daily_portfolio_snapshot_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."daily_portfolio_snapshot_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."daily_portfolio_snapshots" (
    "id" bigint NOT NULL,
    "snapshot_date" "date" NOT NULL,
    "total_purchase_amount" double precision NOT NULL,
    "total_valuation_amount" double precision NOT NULL,
    "profit_amount" double precision NOT NULL,
    "profit_rate" double precision NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" "uuid" NOT NULL,
    "exchange_rate" double precision DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."daily_portfolio_snapshots" OWNER TO "postgres";


ALTER TABLE "public"."daily_portfolio_snapshots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."daily_portfolio_snapshots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exchange_rates" (
    "id" bigint NOT NULL,
    "currency_pair" "text" NOT NULL,
    "rate" double precision NOT NULL,
    "recorded_at" timestamp with time zone NOT NULL,
    "source" "text" DEFAULT 'manual'::"text" NOT NULL
);


ALTER TABLE "public"."exchange_rates" OWNER TO "postgres";


ALTER TABLE "public"."exchange_rates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exchange_rates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."holdings" (
    "id" bigint NOT NULL,
    "asset_id" bigint NOT NULL,
    "currency_code" "text" DEFAULT 'KRW'::"text" NOT NULL,
    "market_updated_at" timestamp with time zone,
    "exchange_code" "text" DEFAULT ''::"text" NOT NULL,
    "name" "text" NOT NULL,
    "symbol" "text" NOT NULL,
    "quantity" double precision NOT NULL,
    "average_price" double precision NOT NULL,
    "current_price" double precision NOT NULL,
    "note" "text" NOT NULL,
    "sort_order" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."holdings" OWNER TO "postgres";


ALTER TABLE "public"."holdings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."holdings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."market_news" (
    "id" bigint NOT NULL,
    "finnhub_id" bigint NOT NULL,
    "category" "text" DEFAULT 'general'::"text" NOT NULL,
    "news_datetime" timestamp with time zone NOT NULL,
    "headline" "text" NOT NULL,
    "image_url" "text" DEFAULT ''::"text" NOT NULL,
    "related" "text" DEFAULT ''::"text" NOT NULL,
    "source" "text" DEFAULT ''::"text" NOT NULL,
    "summary" "text" DEFAULT ''::"text" NOT NULL,
    "url" "text" NOT NULL,
    "fetched_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "raw_payload" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL
);


ALTER TABLE "public"."market_news" OWNER TO "postgres";


ALTER TABLE "public"."market_news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."market_news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."market_news_summaries" (
    "id" bigint NOT NULL,
    "category" "text" DEFAULT 'general'::"text" NOT NULL,
    "model" "text" NOT NULL,
    "news_count" integer DEFAULT 0 NOT NULL,
    "summary_json" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "summary_date" "date" NOT NULL
);


ALTER TABLE "public"."market_news_summaries" OWNER TO "postgres";


ALTER TABLE "public"."market_news_summaries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."market_news_summaries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."portfolio_diagnosis_history" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "model" "text" NOT NULL,
    "analysis_source" "text" NOT NULL,
    "used_fallback" boolean DEFAULT false NOT NULL,
    "ai_error" "text",
    "score" integer NOT NULL,
    "risk_level" "text" NOT NULL,
    "summary" "text" NOT NULL,
    "normalized_portfolio" "jsonb" NOT NULL,
    "diagnosis_json" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "input_tokens" integer,
    "output_tokens" integer,
    "total_tokens" integer,
    "reasoning_tokens" integer,
    "cached_input_tokens" integer,
    "usage_json" "jsonb",
    "openai_request_id" "text",
    "openai_response_id" "text",
    CONSTRAINT "portfolio_diagnosis_history_analysis_source_check" CHECK (("analysis_source" = ANY (ARRAY['openai_model'::"text", 'fallback_rule_based'::"text"]))),
    CONSTRAINT "portfolio_diagnosis_history_risk_level_check" CHECK (("risk_level" = ANY (ARRAY['낮음'::"text", '보통'::"text", '높음'::"text"]))),
    CONSTRAINT "portfolio_diagnosis_history_score_check" CHECK ((("score" >= 0) AND ("score" <= 100)))
);


ALTER TABLE "public"."portfolio_diagnosis_history" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."snapshot_notes" (
    "snapshot_date" "date" NOT NULL,
    "note" "text" DEFAULT ''::"text" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."snapshot_notes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "asset_id" bigint,
    "holding_id" bigint,
    "date" "date" NOT NULL,
    "type" "text" NOT NULL,
    "name" "text" NOT NULL,
    "amount" "text" NOT NULL,
    "quantity" "text" NOT NULL,
    "sort_order" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "uuid" DEFAULT "gen_random_uuid"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."api_tokens"
    ADD CONSTRAINT "api_tokens_pkey" PRIMARY KEY ("provider");



ALTER TABLE ONLY "public"."asset_allocation_targets"
    ADD CONSTRAINT "asset_allocation_targets_asset_id_key" UNIQUE ("asset_id");



ALTER TABLE ONLY "public"."asset_allocation_targets"
    ADD CONSTRAINT "asset_allocation_targets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."asset_allocation_targets"
    ADD CONSTRAINT "asset_allocation_targets_user_id_client_id_key" UNIQUE ("user_id", "client_id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_user_id_client_id_key" UNIQUE ("user_id", "client_id");



ALTER TABLE ONLY "public"."cash_accounts"
    ADD CONSTRAINT "cash_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cash_accounts"
    ADD CONSTRAINT "cash_accounts_user_id_client_id_key" UNIQUE ("user_id", "client_id");



ALTER TABLE ONLY "public"."cash_transactions"
    ADD CONSTRAINT "cash_transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cash_transactions"
    ADD CONSTRAINT "cash_transactions_user_id_client_id_key" UNIQUE ("user_id", "client_id");



ALTER TABLE ONLY "public"."company_news"
    ADD CONSTRAINT "company_news_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company_news_summaries"
    ADD CONSTRAINT "company_news_summaries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company_news"
    ADD CONSTRAINT "company_news_symbol_finnhub_id_key" UNIQUE ("symbol", "finnhub_id");



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_cash_accounts"
    ADD CONSTRAINT "daily_portfolio_snapshot_cash_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_holding_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_holding_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_portfolio_snapshots"
    ADD CONSTRAINT "daily_portfolio_snapshots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."daily_portfolio_snapshots"
    ADD CONSTRAINT "daily_portfolio_snapshots_user_id_snapshot_date_key" UNIQUE ("user_id", "snapshot_date");



ALTER TABLE ONLY "public"."exchange_rates"
    ADD CONSTRAINT "exchange_rates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."holdings"
    ADD CONSTRAINT "holdings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."holdings"
    ADD CONSTRAINT "holdings_user_id_client_id_key" UNIQUE ("user_id", "client_id");



ALTER TABLE ONLY "public"."market_news"
    ADD CONSTRAINT "market_news_finnhub_id_key" UNIQUE ("finnhub_id");



ALTER TABLE ONLY "public"."market_news"
    ADD CONSTRAINT "market_news_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."market_news_summaries"
    ADD CONSTRAINT "market_news_summaries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."portfolio_diagnosis_history"
    ADD CONSTRAINT "portfolio_diagnosis_history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."snapshot_notes"
    ADD CONSTRAINT "snapshot_notes_pkey" PRIMARY KEY ("user_id", "snapshot_date");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_user_id_client_id_key" UNIQUE ("user_id", "client_id");



CREATE INDEX "assets_user_id_deleted_at_idx" ON "public"."assets" USING "btree" ("user_id", "deleted_at");



CREATE INDEX "assets_user_id_idx" ON "public"."assets" USING "btree" ("user_id");



CREATE INDEX "cash_accounts_user_id_deleted_at_idx" ON "public"."cash_accounts" USING "btree" ("user_id", "deleted_at");



CREATE INDEX "cash_accounts_user_id_idx" ON "public"."cash_accounts" USING "btree" ("user_id");



CREATE INDEX "cash_transactions_user_id_deleted_at_idx" ON "public"."cash_transactions" USING "btree" ("user_id", "deleted_at");



CREATE INDEX "cash_transactions_user_id_idx" ON "public"."cash_transactions" USING "btree" ("user_id");



CREATE UNIQUE INDEX "company_news_summaries_company_symbol_date_key" ON "public"."company_news_summaries" USING "btree" ("company_name", "symbol", "summary_date");



CREATE UNIQUE INDEX "company_news_summaries_symbol_date_key" ON "public"."company_news_summaries" USING "btree" ("symbol", "summary_date");



CREATE INDEX "company_news_summaries_symbol_summary_date_idx" ON "public"."company_news_summaries" USING "btree" ("symbol", "summary_date" DESC);



CREATE INDEX "company_news_symbol_datetime_idx" ON "public"."company_news" USING "btree" ("symbol", "news_datetime" DESC);



CREATE INDEX "daily_portfolio_snapshots_user_date_idx" ON "public"."daily_portfolio_snapshots" USING "btree" ("user_id", "snapshot_date" DESC);



CREATE INDEX "holdings_user_id_deleted_at_idx" ON "public"."holdings" USING "btree" ("user_id", "deleted_at");



CREATE INDEX "holdings_user_id_idx" ON "public"."holdings" USING "btree" ("user_id");



CREATE INDEX "idx_cash_accounts_asset_id" ON "public"."cash_accounts" USING "btree" ("asset_id");



CREATE INDEX "idx_cash_transactions_asset_id" ON "public"."cash_transactions" USING "btree" ("asset_id");



CREATE INDEX "idx_cash_transactions_cash_account_id" ON "public"."cash_transactions" USING "btree" ("cash_account_id");



CREATE INDEX "idx_daily_portfolio_snapshots_snapshot_date" ON "public"."daily_portfolio_snapshots" USING "btree" ("snapshot_date");



CREATE INDEX "idx_exchange_rates_currency_pair" ON "public"."exchange_rates" USING "btree" ("currency_pair");



CREATE INDEX "idx_holdings_asset_id" ON "public"."holdings" USING "btree" ("asset_id");



CREATE INDEX "idx_portfolio_diagnosis_history_openai_request_id" ON "public"."portfolio_diagnosis_history" USING "btree" ("openai_request_id");



CREATE INDEX "idx_portfolio_diagnosis_history_openai_response_id" ON "public"."portfolio_diagnosis_history" USING "btree" ("openai_response_id");



CREATE INDEX "idx_snapshot_cash_accounts_snapshot_id" ON "public"."daily_portfolio_snapshot_cash_accounts" USING "btree" ("snapshot_id");



CREATE INDEX "idx_snapshot_holdings_snapshot_id" ON "public"."daily_portfolio_snapshot_holding_items" USING "btree" ("snapshot_id");



CREATE INDEX "idx_snapshot_items_snapshot_id" ON "public"."daily_portfolio_snapshot_items" USING "btree" ("snapshot_id");



CREATE INDEX "idx_transactions_asset_id" ON "public"."transactions" USING "btree" ("asset_id");



CREATE INDEX "idx_transactions_holding_id" ON "public"."transactions" USING "btree" ("holding_id");



CREATE INDEX "market_news_category_datetime_idx" ON "public"."market_news" USING "btree" ("category", "news_datetime" DESC);



CREATE INDEX "market_news_summaries_category_created_at_idx" ON "public"."market_news_summaries" USING "btree" ("category", "created_at" DESC);



CREATE INDEX "market_news_summaries_category_summary_date_idx" ON "public"."market_news_summaries" USING "btree" ("category", "summary_date" DESC);



CREATE UNIQUE INDEX "market_news_summaries_category_summary_date_key" ON "public"."market_news_summaries" USING "btree" ("category", "summary_date");



CREATE INDEX "portfolio_diagnosis_history_source_created_idx" ON "public"."portfolio_diagnosis_history" USING "btree" ("analysis_source", "created_at" DESC);



CREATE INDEX "portfolio_diagnosis_history_user_created_idx" ON "public"."portfolio_diagnosis_history" USING "btree" ("user_id", "created_at" DESC);



CREATE UNIQUE INDEX "snapshot_notes_user_date_idx" ON "public"."snapshot_notes" USING "btree" ("user_id", "snapshot_date");



CREATE INDEX "transactions_user_id_deleted_at_idx" ON "public"."transactions" USING "btree" ("user_id", "deleted_at");



CREATE INDEX "transactions_user_id_idx" ON "public"."transactions" USING "btree" ("user_id");



CREATE UNIQUE INDEX "ux_portfolio_diagnosis_history_user_id" ON "public"."portfolio_diagnosis_history" USING "btree" ("user_id");



CREATE OR REPLACE TRIGGER "asset_allocation_targets_set_updated_at" BEFORE UPDATE ON "public"."asset_allocation_targets" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "assets_set_updated_at" BEFORE UPDATE ON "public"."assets" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "cash_accounts_set_updated_at" BEFORE UPDATE ON "public"."cash_accounts" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "cash_transactions_set_updated_at" BEFORE UPDATE ON "public"."cash_transactions" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "holdings_set_updated_at" BEFORE UPDATE ON "public"."holdings" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "snapshot_notes_set_updated_at" BEFORE UPDATE ON "public"."snapshot_notes" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "transactions_set_updated_at" BEFORE UPDATE ON "public"."transactions" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



ALTER TABLE ONLY "public"."asset_allocation_targets"
    ADD CONSTRAINT "asset_allocation_targets_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."asset_allocation_targets"
    ADD CONSTRAINT "asset_allocation_targets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."assets"
    ADD CONSTRAINT "assets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cash_accounts"
    ADD CONSTRAINT "cash_accounts_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cash_accounts"
    ADD CONSTRAINT "cash_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cash_transactions"
    ADD CONSTRAINT "cash_transactions_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cash_transactions"
    ADD CONSTRAINT "cash_transactions_cash_account_id_fkey" FOREIGN KEY ("cash_account_id") REFERENCES "public"."cash_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cash_transactions"
    ADD CONSTRAINT "cash_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_cash_accounts"
    ADD CONSTRAINT "daily_portfolio_snapshot_cash_accounts_snapshot_id_fkey" FOREIGN KEY ("snapshot_id") REFERENCES "public"."daily_portfolio_snapshots"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_cash_accounts"
    ADD CONSTRAINT "daily_portfolio_snapshot_cash_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_holding_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_holding_items_snapshot_id_fkey" FOREIGN KEY ("snapshot_id") REFERENCES "public"."daily_portfolio_snapshots"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_holding_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_holding_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_items_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_items_snapshot_id_fkey" FOREIGN KEY ("snapshot_id") REFERENCES "public"."daily_portfolio_snapshots"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshot_items"
    ADD CONSTRAINT "daily_portfolio_snapshot_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."daily_portfolio_snapshots"
    ADD CONSTRAINT "daily_portfolio_snapshots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."holdings"
    ADD CONSTRAINT "holdings_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."holdings"
    ADD CONSTRAINT "holdings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."portfolio_diagnosis_history"
    ADD CONSTRAINT "portfolio_diagnosis_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."snapshot_notes"
    ADD CONSTRAINT "snapshot_notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_holding_id_fkey" FOREIGN KEY ("holding_id") REFERENCES "public"."holdings"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Users can read own diagnosis history" ON "public"."portfolio_diagnosis_history" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."asset_allocation_targets" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "asset_allocation_targets_own_rows" ON "public"."asset_allocation_targets" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."assets" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "assets_own_rows" ON "public"."assets" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."cash_accounts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "cash_accounts_own_rows" ON "public"."cash_accounts" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."cash_transactions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "cash_transactions_own_rows" ON "public"."cash_transactions" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."daily_portfolio_snapshot_cash_accounts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "daily_portfolio_snapshot_cash_accounts_own_rows" ON "public"."daily_portfolio_snapshot_cash_accounts" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."daily_portfolio_snapshot_holding_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "daily_portfolio_snapshot_holding_items_own_rows" ON "public"."daily_portfolio_snapshot_holding_items" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."daily_portfolio_snapshot_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "daily_portfolio_snapshot_items_own_rows" ON "public"."daily_portfolio_snapshot_items" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."daily_portfolio_snapshots" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "daily_portfolio_snapshots_own_rows" ON "public"."daily_portfolio_snapshots" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."holdings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "holdings_own_rows" ON "public"."holdings" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."portfolio_diagnosis_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."snapshot_notes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "snapshot_notes_own_rows" ON "public"."snapshot_notes" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "transactions_own_rows" ON "public"."transactions" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."recompute_asset_metrics"("target_user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."api_tokens" TO "anon";
GRANT ALL ON TABLE "public"."api_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."api_tokens" TO "service_role";



GRANT ALL ON TABLE "public"."asset_allocation_targets" TO "anon";
GRANT ALL ON TABLE "public"."asset_allocation_targets" TO "authenticated";
GRANT ALL ON TABLE "public"."asset_allocation_targets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."asset_allocation_targets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."asset_allocation_targets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."asset_allocation_targets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."assets" TO "anon";
GRANT ALL ON TABLE "public"."assets" TO "authenticated";
GRANT ALL ON TABLE "public"."assets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."assets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."assets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."assets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cash_accounts" TO "anon";
GRANT ALL ON TABLE "public"."cash_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."cash_accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cash_accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cash_accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cash_accounts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cash_transactions" TO "anon";
GRANT ALL ON TABLE "public"."cash_transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."cash_transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cash_transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cash_transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cash_transactions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company_news" TO "anon";
GRANT ALL ON TABLE "public"."company_news" TO "authenticated";
GRANT ALL ON TABLE "public"."company_news" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_news_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_news_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_news_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company_news_summaries" TO "anon";
GRANT ALL ON TABLE "public"."company_news_summaries" TO "authenticated";
GRANT ALL ON TABLE "public"."company_news_summaries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_news_summaries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_news_summaries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_news_summaries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_cash_accounts" TO "anon";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_cash_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_cash_accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_cash_accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_cash_accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_cash_accounts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_holding_items" TO "anon";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_holding_items" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_holding_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_holding_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_holding_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_holding_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_items" TO "anon";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_items" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshot_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshot_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."daily_portfolio_snapshots" TO "anon";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshots" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_portfolio_snapshots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."daily_portfolio_snapshots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exchange_rates" TO "anon";
GRANT ALL ON TABLE "public"."exchange_rates" TO "authenticated";
GRANT ALL ON TABLE "public"."exchange_rates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exchange_rates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exchange_rates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exchange_rates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."holdings" TO "anon";
GRANT ALL ON TABLE "public"."holdings" TO "authenticated";
GRANT ALL ON TABLE "public"."holdings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."holdings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."holdings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."holdings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."market_news" TO "anon";
GRANT ALL ON TABLE "public"."market_news" TO "authenticated";
GRANT ALL ON TABLE "public"."market_news" TO "service_role";



GRANT ALL ON SEQUENCE "public"."market_news_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."market_news_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."market_news_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."market_news_summaries" TO "anon";
GRANT ALL ON TABLE "public"."market_news_summaries" TO "authenticated";
GRANT ALL ON TABLE "public"."market_news_summaries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."market_news_summaries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."market_news_summaries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."market_news_summaries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."portfolio_diagnosis_history" TO "anon";
GRANT ALL ON TABLE "public"."portfolio_diagnosis_history" TO "authenticated";
GRANT ALL ON TABLE "public"."portfolio_diagnosis_history" TO "service_role";



GRANT ALL ON TABLE "public"."snapshot_notes" TO "anon";
GRANT ALL ON TABLE "public"."snapshot_notes" TO "authenticated";
GRANT ALL ON TABLE "public"."snapshot_notes" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






