-- Risk-adjusted performance analysis tables.
--
-- Scope:
-- - Create analysis-derived tables only.
-- - Do not update/delete/truncate assets, holdings, transaction_events, or transaction_lines.
-- - Keep core portfolio sync data separate from these derived analysis tables.

create table if not exists public.portfolio_daily_returns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_user_id text not null default 'local',
  return_date date not null,
  beginning_value_krw double precision,
  ending_value_krw double precision not null,
  portfolio_value_krw double precision not null,
  external_cash_flow_krw double precision not null default 0,
  daily_return double precision,
  data_quality text not null default 'complete',
  calculation_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, local_user_id, return_date)
);

create index if not exists portfolio_daily_returns_user_date_idx
  on public.portfolio_daily_returns (user_id, local_user_id, return_date);

alter table public.portfolio_daily_returns enable row level security;

drop policy if exists portfolio_daily_returns_own_rows
  on public.portfolio_daily_returns;

create policy portfolio_daily_returns_own_rows
  on public.portfolio_daily_returns
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.portfolio_daily_returns
  to authenticated;

grant usage, select on sequence public.portfolio_daily_returns_id_seq
  to authenticated;

create table if not exists public.benchmark_prices (
  id bigint generated by default as identity primary key,
  benchmark_code text not null,
  price_date date not null,
  close_price double precision not null,
  adjusted_close_price double precision,
  currency_code text not null default 'KRW',
  fx_rate_to_krw double precision,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (benchmark_code, price_date)
);

create index if not exists benchmark_prices_code_date_idx
  on public.benchmark_prices (benchmark_code, price_date);

alter table public.benchmark_prices enable row level security;

drop policy if exists benchmark_prices_authenticated_read
  on public.benchmark_prices;

create policy benchmark_prices_authenticated_read
  on public.benchmark_prices
  for select
  to authenticated
  using (true);

grant select on public.benchmark_prices to authenticated;

-- Rollback for this migration, if no application code depends on remote derived tables:
--
-- drop table if exists public.portfolio_daily_returns;
-- drop table if exists public.benchmark_prices;
