create table if not exists public.reddit_posts (
  id bigint generated by default as identity primary key,
  reddit_id text not null unique,
  subreddit text not null,
  title text not null,
  body text not null default '',
  url text not null unique,
  author text,
  score integer,
  comment_count integer,
  posted_at timestamptz,
  scraped_at timestamptz not null default now()
);

create index if not exists idx_reddit_posts_subreddit_posted_at
on public.reddit_posts (subreddit, posted_at desc);

create table if not exists public.reddit_comments (
  id bigint generated by default as identity primary key,
  reddit_id text not null unique,
  post_reddit_id text not null references public.reddit_posts (reddit_id) on delete cascade,
  parent_reddit_id text,
  author text,
  body text not null default '',
  score integer,
  posted_at timestamptz,
  scraped_at timestamptz not null default now()
);

create index if not exists idx_reddit_comments_post_reddit_id
on public.reddit_comments (post_reddit_id, posted_at asc);

create table if not exists public.reddit_post_analysis (
  id bigint generated by default as identity primary key,
  post_reddit_id text not null unique references public.reddit_posts (reddit_id) on delete cascade,
  model text not null,
  is_valuable integer not null default 0,
  quality_label text not null,
  confidence double precision,
  tickers_json jsonb not null default '[]'::jsonb,
  post_summary_ko text not null default '',
  comments_summary_ko text not null default '',
  reasons_ko text not null default '',
  raw_json jsonb not null default '{}'::jsonb,
  analyzed_at timestamptz not null default now(),
  title_ko text not null default ''
);

create index if not exists idx_reddit_post_analysis_label
on public.reddit_post_analysis (quality_label, analyzed_at desc);

create table if not exists public.reddit_post_importance (
  id bigint generated by default as identity primary key,
  post_reddit_id text not null unique references public.reddit_posts (reddit_id) on delete cascade,
  model text not null,
  importance_label text not null,
  importance_score integer not null,
  reasons_ko text not null default '',
  raw_json jsonb not null default '{}'::jsonb,
  judged_at timestamptz not null default now(),
  category_label text not null default '기타'
);

create index if not exists idx_reddit_post_importance_score
on public.reddit_post_importance (importance_score desc, judged_at desc);

create table if not exists public.reddit_post_insight (
  id bigint generated by default as identity primary key,
  post_reddit_id text not null unique references public.reddit_posts (reddit_id) on delete cascade,
  model text not null,
  insight_ko text not null default '',
  raw_json jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now()
);

create table if not exists public.reddit_daily_report (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  model text not null,
  post_count integer not null default 0,
  report_ko text not null default '',
  raw_json jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now()
);

create index if not exists idx_reddit_daily_report_generated_at
on public.reddit_daily_report (generated_at desc);

create table if not exists public.rag_summary_embeddings (
  id bigint generated by default as identity primary key,
  source_type text not null,
  source_id text not null,
  chunk_index integer not null default 0,
  text text not null,
  text_hash text not null,
  embedding_model text not null,
  embedding_dim integer not null,
  embedding_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_type, source_id, chunk_index, embedding_model)
);

create index if not exists idx_rag_summary_embeddings_source
on public.rag_summary_embeddings (source_type, source_id);

create index if not exists idx_rag_summary_embeddings_model
on public.rag_summary_embeddings (embedding_model, updated_at desc);

create or replace view public.reddit_post_full
with (security_invoker = true) as
select
  p.id,
  p.reddit_id,
  p.subreddit,
  p.title,
  p.body,
  p.url,
  p.author,
  p.score,
  p.comment_count,
  p.posted_at,
  p.scraped_at,
  a.model as analysis_model,
  a.is_valuable,
  a.quality_label,
  a.confidence,
  a.tickers_json,
  a.title_ko,
  a.post_summary_ko,
  a.comments_summary_ko,
  a.reasons_ko as analysis_reasons_ko,
  a.analyzed_at,
  i.model as importance_model,
  i.importance_label,
  i.importance_score,
  i.category_label,
  i.reasons_ko as importance_reasons_ko,
  i.judged_at,
  s.model as insight_model,
  s.insight_ko,
  s.generated_at as insight_generated_at
from public.reddit_posts p
left join public.reddit_post_analysis a
  on a.post_reddit_id = p.reddit_id
left join public.reddit_post_importance i
  on i.post_reddit_id = p.reddit_id
left join public.reddit_post_insight s
  on s.post_reddit_id = p.reddit_id;

alter table public.reddit_posts enable row level security;
alter table public.reddit_comments enable row level security;
alter table public.reddit_post_analysis enable row level security;
alter table public.reddit_post_importance enable row level security;
alter table public.reddit_post_insight enable row level security;
alter table public.reddit_daily_report enable row level security;
alter table public.rag_summary_embeddings enable row level security;

revoke insert, update, delete, truncate, references, trigger
on table
  public.reddit_posts,
  public.reddit_comments,
  public.reddit_post_analysis,
  public.reddit_post_importance,
  public.reddit_post_insight,
  public.reddit_daily_report,
  public.rag_summary_embeddings
from anon, authenticated;

grant select
on table
  public.reddit_posts,
  public.reddit_comments,
  public.reddit_post_analysis,
  public.reddit_post_importance,
  public.reddit_post_insight,
  public.reddit_daily_report,
  public.rag_summary_embeddings,
  public.reddit_post_full
to anon, authenticated;

create policy reddit_posts_public_read
on public.reddit_posts
for select
to anon, authenticated
using (true);

create policy reddit_comments_public_read
on public.reddit_comments
for select
to anon, authenticated
using (true);

create policy reddit_post_analysis_public_read
on public.reddit_post_analysis
for select
to anon, authenticated
using (true);

create policy reddit_post_importance_public_read
on public.reddit_post_importance
for select
to anon, authenticated
using (true);

create policy reddit_post_insight_public_read
on public.reddit_post_insight
for select
to anon, authenticated
using (true);

create policy reddit_daily_report_public_read
on public.reddit_daily_report
for select
to anon, authenticated
using (true);

create policy rag_summary_embeddings_public_read
on public.rag_summary_embeddings
for select
to anon, authenticated
using (true);
