create table if not exists public.transaction_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid default gen_random_uuid(),
  occurred_at date not null,
  kind text not null,
  title text not null default '',
  memo text not null default '',
  source text not null default 'manual',
  legacy_source_table text,
  legacy_source_id bigint,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone
);

create table if not exists public.transaction_lines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id bigint not null references public.transaction_events(id) on delete cascade,
  asset_id bigint references public.assets(id) on delete set null,
  holding_id bigint references public.holdings(id) on delete set null,
  cash_account_id bigint references public.cash_accounts(id) on delete set null,
  client_id uuid default gen_random_uuid(),
  legacy_source_table text,
  legacy_source_id bigint,
  action text not null,
  currency_code text not null default 'KRW',
  quantity_delta double precision not null default 0,
  cash_delta double precision not null default 0,
  unit_price double precision not null default 0,
  gross_amount double precision not null default 0,
  fee_amount double precision not null default 0,
  tax_amount double precision not null default 0,
  cost_basis_delta double precision not null default 0,
  realized_pnl double precision not null default 0,
  fx_rate double precision,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone
);

alter table only public.transaction_events
  add constraint transaction_events_user_id_client_id_key
  unique (user_id, client_id);

alter table only public.transaction_lines
  add constraint transaction_lines_user_id_client_id_key
  unique (user_id, client_id);

create index if not exists transaction_events_user_id_deleted_at_idx
  on public.transaction_events using btree (user_id, deleted_at);

create index if not exists transaction_events_user_id_occurred_at_idx
  on public.transaction_events using btree (user_id, occurred_at desc);

create index if not exists transaction_events_user_id_kind_idx
  on public.transaction_events using btree (user_id, kind);

create index if not exists transaction_lines_user_id_deleted_at_idx
  on public.transaction_lines using btree (user_id, deleted_at);

create index if not exists transaction_lines_event_id_idx
  on public.transaction_lines using btree (event_id);

create index if not exists transaction_lines_holding_id_idx
  on public.transaction_lines using btree (holding_id);

create index if not exists transaction_lines_cash_account_id_idx
  on public.transaction_lines using btree (cash_account_id);

create or replace trigger transaction_events_set_updated_at
  before update on public.transaction_events
  for each row execute function public.set_updated_at();

create or replace trigger transaction_lines_set_updated_at
  before update on public.transaction_lines
  for each row execute function public.set_updated_at();

alter table public.transaction_events enable row level security;
alter table public.transaction_lines enable row level security;

drop policy if exists transaction_events_own_rows
  on public.transaction_events;
create policy transaction_events_own_rows on public.transaction_events
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists transaction_lines_own_rows
  on public.transaction_lines;
create policy transaction_lines_own_rows on public.transaction_lines
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant all on table public.transaction_events to anon;
grant all on table public.transaction_events to authenticated;
grant all on table public.transaction_events to service_role;
grant all on sequence public.transaction_events_id_seq to anon;
grant all on sequence public.transaction_events_id_seq to authenticated;
grant all on sequence public.transaction_events_id_seq to service_role;

grant all on table public.transaction_lines to anon;
grant all on table public.transaction_lines to authenticated;
grant all on table public.transaction_lines to service_role;
grant all on sequence public.transaction_lines_id_seq to anon;
grant all on sequence public.transaction_lines_id_seq to authenticated;
grant all on sequence public.transaction_lines_id_seq to service_role;

comment on table public.transaction_events is
  'User-visible transaction events for the normalized ledger redesign.';
comment on table public.transaction_lines is
  'Calculation-ready ledger lines generated from transaction events.';
comment on column public.transaction_events.kind is
  'Stable event category such as trade, cash_flow, cash_transfer, fx_exchange, income, fee, tax, adjustment, or opening_balance.';
comment on column public.transaction_lines.action is
  'Stable line action such as buy, sell, settlement, deposit, withdrawal, transfer_out, transfer_in, fx_out, fx_in, dividend, interest, fee, tax, realized_pnl, or adjustment.';
